import { jsPDF } from 'jspdf';
import { saveAs } from 'file-saver';
import type { Prediction } from '../types';

export const exportSinglePredictionToPDF = (prediction: Prediction) => {
  const doc = new jsPDF();
  const lineHeight = 10;
  let currentY = 20;

  // Helper to add a new line of text
  const addLine = (text: string, indent = 0) => {
    if (currentY >= 280) {
      doc.addPage();
      currentY = 20;
    }
    doc.text(text, 20 + indent, currentY);
    currentY += lineHeight;
  };

  // Title
  doc.setFontSize(20);
  doc.setTextColor(0, 0, 0);
  addLine('HeartGuard AI - Prediction Report');
  currentY += 10;

  // Basic Information
  doc.setFontSize(14);
  doc.setTextColor(0, 102, 204);
  addLine('Basic Information');
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  addLine(`Date: ${new Date(prediction.prediction_date).toLocaleDateString()}`, 10);
  addLine(`Result: ${prediction.prediction_result ? 'High Risk' : 'Low Risk'}`, 10);
  currentY += 5;

  // Physical Metrics
  doc.setFontSize(14);
  doc.setTextColor(0, 102, 204);
  addLine('Physical Metrics');
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  addLine(`BMI: ${prediction.bmi}`, 10);
  addLine(`Physical Health (days/month): ${prediction.physical_health}`, 10);
  addLine(`Mental Health (days/month): ${prediction.mental_health}`, 10);
  addLine(`Sleep Time (hours): ${prediction.sleep_time}`, 10);
  currentY += 5;

  // Demographics
  doc.setFontSize(14);
  doc.setTextColor(0, 102, 204);
  addLine('Demographics');
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  addLine(`Sex: ${prediction.sex}`, 10);
  addLine(`Age Category: ${prediction.age_category}`, 10);
  addLine(`Race: ${prediction.race}`, 10);
  currentY += 5;

  // Health Conditions
  doc.setFontSize(14);
  doc.setTextColor(0, 102, 204);
  addLine('Health Conditions');
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  addLine(`Smoking: ${prediction.smoking ? 'Yes' : 'No'}`, 10);
  addLine(`Alcohol Drinking: ${prediction.alcohol_drinking ? 'Yes' : 'No'}`, 10);
  addLine(`Previous Stroke: ${prediction.stroke ? 'Yes' : 'No'}`, 10);
  addLine(`Difficulty Walking: ${prediction.diff_walking ? 'Yes' : 'No'}`, 10);
  addLine(`Diabetic: ${prediction.diabetic ? 'Yes' : 'No'}`, 10);
  addLine(`Asthma: ${prediction.asthma ? 'Yes' : 'No'}`, 10);
  addLine(`Kidney Disease: ${prediction.kidney_disease ? 'Yes' : 'No'}`, 10);
  addLine(`Skin Cancer: ${prediction.skin_cancer ? 'Yes' : 'No'}`, 10);
  currentY += 5;

  // Lifestyle
  doc.setFontSize(14);
  doc.setTextColor(0, 102, 204);
  addLine('Lifestyle');
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  addLine(`Physical Activity: ${prediction.physical_activity ? 'Yes' : 'No'}`, 10);
  addLine(`General Health: ${prediction.gen_health}`, 10);

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by HeartGuard AI', 20, 290);
  doc.text(new Date().toLocaleString(), 150, 290);

  doc.save(`prediction-report-${new Date(prediction.prediction_date).toLocaleDateString()}.pdf`);
};

export const exportToPDF = (predictions: Prediction[]) => {
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(20);
  doc.text('HeartGuard AI - Prediction History', 20, 20);
  
  // Add date
  doc.setFontSize(12);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 30);
  
  // Add predictions
  doc.setFontSize(10);
  predictions.forEach((prediction, index) => {
    const y = 40 + (index * 10);
    if (y >= 280) {
      doc.addPage();
      doc.setFontSize(10);
    }
    
    const date = new Date(prediction.prediction_date).toLocaleDateString();
    const result = prediction.prediction_result ? 'High Risk' : 'Low Risk';
    
    doc.text(`Date: ${date}`, 20, y);
    doc.text(`Result: ${result}`, 80, y);
    doc.text(`BMI: ${prediction.bmi}`, 140, y);
  });
  
  doc.save('prediction-history.pdf');
};

export const exportToCSV = (predictions: Prediction[]) => {
  const headers = [
    'Date',
    'Result',
    'BMI',
    'Smoking',
    'Alcohol',
    'Stroke',
    'Physical Health',
    'Mental Health',
    'Difficulty Walking',
    'Sex',
    'Age Category',
    'Race',
    'Diabetic',
    'Physical Activity',
    'General Health',
    'Sleep Time',
    'Asthma',
    'Kidney Disease',
    'Skin Cancer'
  ].join(',');

  const rows = predictions.map(p => [
    new Date(p.prediction_date).toLocaleDateString(),
    p.prediction_result ? 'High Risk' : 'Low Risk',
    p.bmi,
    p.smoking ? 'Yes' : 'No',
    p.alcohol_drinking ? 'Yes' : 'No',
    p.stroke ? 'Yes' : 'No',
    p.physical_health,
    p.mental_health,
    p.diff_walking ? 'Yes' : 'No',
    p.sex,
    p.age_category,
    p.race,
    p.diabetic ? 'Yes' : 'No',
    p.physical_activity ? 'Yes' : 'No',
    p.gen_health,
    p.sleep_time,
    p.asthma ? 'Yes' : 'No',
    p.kidney_disease ? 'Yes' : 'No',
    p.skin_cancer ? 'Yes' : 'No'
  ].join(','));

  const csvContent = [headers, ...rows].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8' });
  saveAs(blob, 'prediction-history.csv');
};