import { jsPDF } from 'jspdf';
import type { RiskFactor } from '../types';

export const generateHealthReport = (data: {
  metrics: {
    heartRate: string;
    bmi: string;
    bloodPressure: string;
    bloodSugar: string;
  };
  riskFactors: RiskFactor[];
  lastCheck: {
    cholesterol: string;
    bloodSugar: string;
    bloodPressure: string;
    heartRate: string;
    date: string;
  };
}) => {
  const doc = new jsPDF();
  const lineHeight = 10;
  let currentY = 20;

  // Helper to add a new line of text
  const addLine = (text: string, indent = 0) => {
    if (currentY >= 280) {
      doc.addPage();
      currentY = 20;
    }
    doc.text(text, 20 + indent, currentY);
    currentY += lineHeight;
  };

  // Title
  doc.setFontSize(20);
  doc.setTextColor(0, 0, 0);
  addLine('HeartGuard AI - Health Report');
  currentY += 10;

  // Date
  doc.setFontSize(12);
  addLine(`Report Generated: ${new Date().toLocaleDateString()}`);
  currentY += 10;

  // Current Metrics
  doc.setFontSize(16);
  doc.setTextColor(0, 102, 204);
  addLine('Current Health Metrics');
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  addLine(`Heart Rate: ${data.metrics.heartRate}`, 10);
  addLine(`BMI: ${data.metrics.bmi}`, 10);
  addLine(`Blood Pressure: ${data.metrics.bloodPressure}`, 10);
  addLine(`Blood Sugar: ${data.metrics.bloodSugar}`, 10);
  currentY += 10;

  // Risk Factors
  doc.setFontSize(16);
  doc.setTextColor(0, 102, 204);
  addLine('Risk Factor Analysis');
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  data.riskFactors.forEach(factor => {
    addLine(`${factor.name}: ${factor.value}`, 10);
    addLine(`Risk Level: ${factor.level}`, 20);
    addLine(`Recommendation: ${factor.recommendation}`, 20);
    currentY += 5;
  });
  currentY += 10;

  // Latest Health Check
  doc.setFontSize(16);
  doc.setTextColor(0, 102, 204);
  addLine('Latest Health Check Results');
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  addLine(`Date: ${data.lastCheck.date}`, 10);
  addLine(`Cholesterol: ${data.lastCheck.cholesterol}`, 10);
  addLine(`Blood Sugar: ${data.lastCheck.bloodSugar}`, 10);
  addLine(`Blood Pressure: ${data.lastCheck.bloodPressure}`, 10);
  addLine(`Heart Rate: ${data.lastCheck.heartRate}`, 10);

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by HeartGuard AI', 20, 290);
  doc.text(new Date().toLocaleString(), 150, 290);

  // Save the PDF
  doc.save('health-report.pdf');
};